language: python
python:
  - "3.8"

services:
  - docker
  -
cache: pip
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."

script:
  - pytest

after_success:
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
  - docker buildx build --platform linux/arm/v7 \-t pepeloperena/helloworld:testtag --push .